import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Jenny",
      email: "Jenny@sample.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: "true",
    },
    {
      name: "Tommy",
      email: "Tommy@sample.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: "false",
    },
    {
      name: "Tommy Lee",
      email: "TommyLee@sample.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: "false",
    },
  ],
  career: [
    {
      title: "잘나가던 개발자, 스타트업 투자사로?",
      filter: "아티클",
      img: "https://res.cloudinary.com/jenniecloud/image/upload/v1636343157/career/campaign-creators-gMsnXqILjp4-unsplash_achrfb.jpg",
      startAt: "2021-11-08",
      endAt: "2021-11-10",
      tags: ["#Higher Edit", "커리어", "시리즈"],
      content:
        "sample content this story, this is only sample data for structure. therefore, it means nothing....!!!!!!!",
      createdAt: Date.now(),
    },
    {
      title: "구성원을 사로잡는 온보딩 비결: Talk #54",
      filter: ["아티클"],
      img: "https://res.cloudinary.com/jenniecloud/image/upload/v1636343157/career/campaign-creators-gMsnXqILjp4-unsplash_achrfb.jpg",
      startAt: "2021-11-08",
      endAt: "2021-11-10",
      tags: ["#Higher Edit", "커리어", "시리즈"],
      content:
        "sample content this story, this is only sample data for structure. therefore, it means nothing....!!!!!!!",
      createdAt: Date.now(),
    },
    {
      title: "마이리얼트림이 디자인으로 고객과 소통하는 방법",
      filter: ["아티클"],
      img: "https://res.cloudinary.com/jenniecloud/image/upload/v1636343158/career/ant-rozetsky-HXOllTSwrpM-unsplash_t6bzzy.jpg",
      startAt: "2021-11-08",
      endAt: "2021-11-10",
      tags: ["#Higher Edit", "커리어", "시리즈"],
      content:
        "sample content this story, this is only sample data for structure. therefore, it means nothing....!!!!!!!",
      createdAt: Date.now(),
    },
  ],
  jobList: [
    {
      company: "악어디지털",
      position: "font-end",
      createAt: "2021-10-24T15:00:00Z",
      expire: "2021-10-29T15:00:00Z",
      description: "we are hiring this kind of people....who ",
      introduction: "우리는 이런 회사입니다.환영합니다.",
      category: ["IT", "Marketing", "HR"],
      title: "신입 front-end 개발자 채용합니다.",
      experiment: 0,
      url: "https://res.cloudinary.com/jenniecloud/image/upload/v1635225319/images/amy-hirschi-szrJ3wjzOMg-unsplash_if1ku8.jpg",
      tags: ["조식제공", "워크샵", "중식제공", "육아휴직", "사내동호회"],
      address: "서울특별시",
    },
    {
      company: "버킷플레이스(오늘의 집)",
      position: "font-end",
      createAt: "2021-10-24T15:00:00Z",
      expire: "2021-10-29T15:00:00Z",
      description:
        "오늘의집이 도전하고 있는 리빙 시장은 총 규모 10조 이상의 거대한 시장입니다. 가구, 소품, 인테리어 시공 등 많은 영역들이 아직까지 지역 중심의 오프라인 모델로 남아있어 발전 가능성이 무궁무진한 분야이기도 합니다",
      introduction:
        "버킷플레이스(오늘의집)는 라이프 커머스 분야에서 빠르게 성장하는 기업입니다. 우리는 고객, 직원, 파트너 그리고 우리를 아는 모든 사람들의 일상을 어떻게 변화시킬 수 있는지 매 순간 고민합니다.",
      category: ["IT", "Marketing", "HR"],
      title: "Platform Web Frontend Developer",
      experiment: 0,
      url: "https://res.cloudinary.com/jenniecloud/image/upload/v1635225319/images/amy-hirschi-szrJ3wjzOMg-unsplash_if1ku8.jpg",
      tags: [
        "조식제공",
        "워크샵",
        "중식제공",
        "과일",
        " 휴계실",
        "리프레시 휴가",
      ],
      address: "서울특별시",
    },
    {
      company: "지니프릭스",
      position: "font-end",
      createAt: "2021-10-24T15:00:00Z",
      expire: "2021-10-29T15:00:00Z",
      description: "we are hiring this kind of people....who ",
      introduction: "우리는 이런 회사입니다.환영합니다.",
      category: ["IT", "Marketing", "HR"],
      title: "신입 front-end 개발자 채용합니다.",
      experiment: 0,
      url: "https://res.cloudinary.com/jenniecloud/image/upload/v1635225320/images/firmbee-com-gcsNOsPEXfs-unsplash_hnm6mz.jpg",
      tags: ["조식제공", "워크샵", "중식제공", "육아휴직", "사내동호회"],
      address: "서울특별시",
    },
    {
      company: "코빗(Korbit)",
      position: "server developer",
      createAt: "2021-10-23T15:00:00Z",
      expire: "2021-10-29T15:00:00Z",
      description:
        "신사업 백엔드 개발자는 가상자산 거래소 코빗에서 새로운 서비스의 Back-End를 개발하는 업무를 맡게 됩니다. 가상자산 시장에 관한 정보를 제공하는 서비스나 가상자산 거래를 도와주는 새로운 방식의 서비스 등, 기존의 가상자산 거래소에서는 찾아보기 어려웠던 새로운 서비스를 함께 개발하실 분을 찾습니다",
      introduction:
        "코빗은 한국 최초의 가상자산 거래소로 가상자산 거래 및 그 외 비트코인, 이더리움 등 가상자산을 이용한 다양한 사업을 진행하고 있는 핀테크 기업입니다. 2013년 설립 이래 한국과 실리콘밸리의 유수 벤처 캐피털의 투자를 유치해 성장의 발판을 튼튼하게 마련해왔으며, 2017년 NEXON의 지주사 NXC에 인수되어 더욱 튼튼한 자본을 갖추고 코빗만의 노하우를 바탕으로 가상자산 거래소를 운영하고 있습니다 ",
      category: ["IT", "Marketing", "HR"],
      title: "신입 front-end 개발자 채용합니다.",
      experiment: 3,
      url: "https://res.cloudinary.com/jenniecloud/image/upload/v1635225340/images/windows-4nSKsoYyuPQ-unsplash_hi7cyp.jpg",
      tags: [
        "금융",
        "스타트업",
        "중식제공",
        "과일",
        " 휴계실",
        "리프레시 휴가",
      ],
      address: "서울특별시",
    },
    {
      company: "세컨신드롬",
      position: "front-end",
      createAt: "2021-10-26T15:00:00Z",
      expire: "2021-10-31T15:00:00Z",
      description:
        "주요업무 미니창고 다락 서비스 프론트엔드 개발 내부 운영을 위한 백오피스 도구 개발 프론트엔드 Product 개발의 오너십을 가지고 모든 프로세스에 참여 더 나은 사용자 경험을 위한 챕터/스쿼드 구성원들과의 자유토론과 협업.",
      introduction:
        "[Second Syndrome] '어디서든 쾌적한 주거생활 '세컨신드롬은 인프라테크로 우리 주거생활을 조금 더 자유롭게 바꾸고자 합니다. 오르기만 하는 집세에 우리는 매번 살 집을 찾아 헤매이고 고민합니다. 집에서 머무는 시간이 늘고 집에서 하는 활동도 많아졌는데, 쾌적하고 넓은 집에서 이사 좀 안 가고 편안하게 살 순 없을까요? 방 한칸, 공간 한평이 필요해졌을 때 갑자기 큰집으로 이사를 간다는 건 너무나 힘든 일이죠!",
      category: ["IT", "Marketing"],
      title: "[미니창고 다락] 프론트엔드 개발자",
      experiment: 3,
      url: "https://res.cloudinary.com/jenniecloud/image/upload/v1635225360/images/slidebean-TpGIpUF67po-unsplash_satr5e.jpg",
      tags: [
        "연봉상위6%~10%",
        "인원급성장",
        "50명이하",
        " 휴계실",
        "리프레시 휴가",
        "건강검진",
      ],
      address: "서울특별시",
    },
    {
      company: "울타리 코리아",
      position: "front-end",
      createAt: "2021-11-08T15:00:00Z",
      expire: "2021-11-20T15:00:00Z",
      description:
        "Wooltari는 한국 product을 미국 현지 고객들에게 온라인/오프라인으로 유통 및 판매를 하는 회사입니다. 본사는 미국 캘리포니아에 있으며 온라인 사업팀은 현재 서울 강남에 있습니다. 현재 프라이머 사제 펀드, 스피겐, 블루스톤 등의 투자회사로부터 투자를 받아 매출이 매달 월 20% 이상 오르고 있는 급성장하는 회사이며 저희와 함께 빠르게 성장하시면서 많은 경험을 하실 수 있을 거라 생각됩니다.",
      introduction:
        "Wooltari 팀의 확장을 함께 준비하고 성장해 나갈 멋진 Shopfiy 개발자를 찾습니다.",
      category: ["IT", "Marketing"],
      title: "Shopify Plus 개발자",
      experiment: 3,
      url: "https://res.cloudinary.com/jenniecloud/image/upload/v1636343157/career/campaign-creators-gMsnXqILjp4-unsplash_achrfb.jpg",
      tags: ["스타트업", "음료", "간식", "원격근무", "판매, 유통"],
      address: "서울특별시 서초구 서초대로 77길 17",
    },
    {
      company: "포디리플레이코리아",
      position: "Back-end",
      createAt: "2021-11-08T15:00:00Z",
      expire: "2021-11-20T15:00:00Z",
      description:
        "4DREPLAY는 미국 실리콘밸리에 본사를 두고 있으며, 한국과 일본에 각각 법인을 둔 글로벌 스타트업입니다. 본격적인 글로벌 시장 공략을 위해 2016년 미국 실리콘밸리에 법인을 설립, 진출GKDU, 시장에서 꾸준히 기술력을 인정받고 있습니다. 전 세계에서 근무하고 있는 4DREPLAY의 Global One Team은 차별화된 경험을 제공하기 위해 시간과 공간을 초월한 협업을 바탕으로 끊임없이 발전하고 있습니다.  ",
      introduction:
        "DREPLAY, Frontier Technology Company Pioneering technology innovation delivers Rich Multimedia Experiences and drives Global Standards .",
      category: ["IT", "Marketing"],
      title: "Web Back-End Engineer",
      experiment: 3,
      url: "https://res.cloudinary.com/jenniecloud/image/upload/v1635247812/images/startup-849804_640_yvgfme.jpg",
      tags: [
        "연봉상위 6~10%",
        "인원급성장",
        "51~300명",
        "설립4~9년",
        "스톡옵션",
        "커피",
        "간식",
        "IT",
      ],
      address: "강남구 광평로280 로즈데일빌딩 10층",
    },
  ],
};

export default data;
